version: '3.9'
services: 
  database:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=johndoe-colors
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - internal_network
  backend: 
    build: backend/.
    depends_on:
      - database
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    networks:
      - internal_network
  frontend:
    build: frontend/.
    ports: 
      - "4173:4173"
   
    
volumes:
  pgdata:

networks:
  internal_network:
    driver: bridge